export const cardContent = [
  {
    picNum: 1,
    headingNum: 1,
    backNum: 1,
    title: "The Sea Explorer",
    slugA: "React",
    slugB: "Javascript",
    slugC: "CSS3",
    slugD: "API",
    slugE: "Difficulty: Easy",
    backTitle: "Only",
    backSubtitle: "$297",
  },
  {
    picNum: 2,
    headingNum: 2,
    backNum: 2,
    title: "The Forest Hiker",
    slugA: "3 Day Tour",
    slugB: "Up to 30 People",
    slugC: "2 Tour Guides",
    slugD: "Sleep in Cozy Hotels",
    slugE: "Difficulty: Easy",
    backTitle: "Only",
    backSubtitle: "$497",
  },
  {
    picNum: 3,
    headingNum: 3,
    backNum: 3,
    title: "The Snow Adventurer",
    slugA: "3 Day Tour",
    slugB: "Up to 30 People",
    slugC: "2 Tour Guides",
    slugD: "Sleep in Cozy Hotels",
    slugE: "Difficulty: Easy",
    backTitle: "Only",
    backSubtitle: "$697",
  },
  {
    picNum: 3,
    headingNum: 3,
    backNum: 3,
    title: "The Snow Adventurer",
    slugA: "3 Day Tour",
    slugB: "Up to 30 People",
    slugC: "2 Tour Guides",
    slugD: "Sleep in Cozy Hotels",
    slugE: "Difficulty: Easy",
    backTitle: "Only",
    backSubtitle: "$697",
  },
  {
    picNum: 2,
    headingNum: 2,
    backNum: 2,
    title: "The Forest Hiker",
    slugA: "3 Day Tour",
    slugB: "Up to 30 People",
    slugC: "2 Tour Guides",
    slugD: "Sleep in Cozy Hotels",
    slugE: "Difficulty: Easy",
    backTitle: "Only",
    backSubtitle: "$497",
  },
  {
    picNum: 3,
    headingNum: 3,
    backNum: 3,
    title: "The Snow Adventurer",
    slugA: "3 Day Tour",
    slugB: "Up to 30 People",
    slugC: "2 Tour Guides",
    slugD: "Sleep in Cozy Hotels",
    slugE: "Difficulty: Easy",
    backTitle: "Only",
    backSubtitle: "$697",
  },
  {
    picNum: 3,
    headingNum: 3,
    backNum: 3,
    title: "The Snow Adventurer",
    slugA: "3 Day Tour",
    slugB: "Up to 30 People",
    slugC: "2 Tour Guides",
    slugD: "Sleep in Cozy Hotels",
    slugE: "Difficulty: Easy",
    backTitle: "Only",
    backSubtitle: "$697",
  },
  {
    picNum: 2,
    headingNum: 2,
    backNum: 2,
    title: "The Forest Hiker",
    slugA: "3 Day Tour",
    slugB: "Up to 30 People",
    slugC: "2 Tour Guides",
    slugD: "Sleep in Cozy Hotels",
    slugE: "Difficulty: Easy",
    backTitle: "Only",
    backSubtitle: "$497",
  },
  {
    picNum: 3,
    headingNum: 3,
    backNum: 3,
    title: "The Snow Adventurer",
    slugA: "3 Day Tour",
    slugB: "Up to 30 People",
    slugC: "2 Tour Guides",
    slugD: "Sleep in Cozy Hotels",
    slugE: "Difficulty: Easy",
    backTitle: "Only",
    backSubtitle: "$697",
  },
];
